/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleGCMS;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("commitei");
    	return true;
    }
}
